### ISSUE TITLE
unable to install on ubuntu 16.04

### ISSUE THREAD

**Issue by mark-hahn** [node-serialport/node-serialport#1418]
- __SerialPort Version__:  1.7.4 
- __NodeJS Version__: v8.9.3
- __Operating System__ and __Hardware Platform__: Ubuntu server 16.04 on x64

- Have you checked the right __version__ of the __api docs?__:  yes
- Are you having trouble installing and you checked the __Installation Special Cases__ docs?  yes
- Are you using __Electron__ and have you checked the _Electron Docs_?: not using electron

### Summary of Problem

Error when trying to install serialport.

### Steps and Code to Reproduce the Issue

Run `npm install --unsafe-perm serialport` as root.

I always run as root on this server (no lectures please).  I have been using serialport in this environment for years with no problem.  But I rebuilt the server from scratch using newer node version and I can't get past this error ...

```
> serialport@1.7.4 install /archive/dev/apps/hvac2/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/root/.nvm/versions/node/v8.9.3/bin/node',
node-pre-gyp verb cli   '/archive/dev/apps/hvac2/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.7
node-pre-gyp info using node@8.9.3 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/archive/dev/apps/hvac2/node_modules/serialport/build/serialport/v1.7.4/Release/node-v57-linux-x64/serialport.node" (not found)
node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (module.js:536:15)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:466:25)
node-pre-gyp ERR! stack     at Module.require (module.js:579:17)
node-pre-gyp ERR! stack     at require (internal/module.js:11:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:31:26
node-pre-gyp ERR! stack     at Object.<anonymous> (/archive/dev/apps/hvac2/node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:635:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:646:10)
node-pre-gyp ERR! stack     at Module.load (module.js:554:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:497:12)
node-pre-gyp ERR! System Linux 4.4.0-87-generic
node-pre-gyp ERR! command "/root/.nvm/versions/node/v8.9.3/bin/node" "/archive/dev/apps/hvac2/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /archive/dev/apps/hvac2/node_modules/serialport
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the serialport@1.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-11T08_24_31_217Z-debug.log

srv(~/dev/apps/hvac2/node_mod
```

**Comment by mark-hahn** [comment]
Closing this for now because I think I am missing some gyp dependencies.

**Comment by mark-hahn** [comment]
I just created a fresh directory and ran `npm install serialport --unsafe-perm`.  It installed serialport using a prebuilt binary.  So the problem has something to do with my npm module dependencies in my particular project.

I just deleted my node-modules/serialport directory and did a global install and everything works fine now.
