### ISSUE TITLE
ARMv7: Can't compile

### ISSUE THREAD

**Issue by marconett** [node-serialport/node-serialport#1529]
- SerialPort Version: 6.1.1
- NodeJS Version: 9.9.0
- Python Version: 2.7.9
- Hardware: https://en.wikipedia.org/wiki/CHIP_(computer)
- OS/Architecture: Linux chip 4.4.13-ntc-mlc #1 SMP Tue Dec 6 21:38:00 UTC 2016 armv7l GNU/Linux
- Debian 8.10

- Are you having trouble installing and you checked the __Installation Special Cases__ docs? yes

### Summary of Problem

I'm using Node from deb.nodesource.com and the command `npm install serialport --save --unsafe-perm --build-from-source` as non-root user. I installed `build-essential` and `python-dev` as well.

Output is the following:

```
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.13-ntc-mlc
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chip/row/node_modules/serialport
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.1.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@6.1.1 install script.
```

Debug-Log looks like the following:

```
4705 verbose stack Error: serialport@6.1.1 install: `prebuild-install || node-gyp rebuild`
4705 verbose stack Exit status 1
4705 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
4705 verbose stack     at EventEmitter.emit (events.js:180:13)
4705 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4705 verbose stack     at ChildProcess.emit (events.js:180:13)
4705 verbose stack     at maybeClose (internal/child_process.js:936:16)
4705 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
4706 verbose pkgid serialport@6.1.1
4707 verbose cwd /home/chip/row
4708 verbose Linux 4.4.13-ntc-mlc
4709 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "serialport" "--save" "--unsafe-perm" "--build-from-source"
4710 verbose node v9.9.0
4711 verbose npm  v5.6.0
4712 error code ELIFECYCLE
4713 error errno 1
4714 error serialport@6.1.1 install: `prebuild-install || node-gyp rebuild`
4714 error Exit status 1
4715 error Failed at the serialport@6.1.1 install script.
```

I tried SerialPort 6.1.1 and also an older version (4.0.7) but ran into the same problem. I've also tried different node versions (6 and 8) to no avail.

I don't think it's the hardware as #852 hints at it working on the chip. I don't really know what to do, it just doesn't seem to start compiling..

**Comment by marconett** [comment]
well.. it was related to locales not being set. weird, but someone else had the same problem: https://github.com/nodejs/node-gyp/issues/1283
