### ISSUE TITLE
build failing for on ARM Cortex A9

### ISSUE THREAD

**Issue by mateodelnorte** [node-serialport/node-serialport#1706]
I'm attempting to build this module for use on an ARM Cortex A9. The build is failing with the below logs. 

Any tips on getting this working?

```
> @serialport/bindings@2.0.2 install /node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=10.4.1 runtime=node arch=arm platform=linux)
make: Entering directory '/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
../src/serialport_unix.cpp:24:26: fatal error: linux/serial.h: No such file or directory
 #include <linux/serial.h>
                          ^
compilation terminated.
make: *** [bindings.target.mk:96: Release/obj.target/bindings/src/serialport_unix.o] Error 1
```

Thanks.

**Comment by mateodelnorte** [comment]
Looks like this was because I missed some alpine linux requirements in my Dockerfile. https://github.com/node-serialport/node-serialport/blob/4318c253832a164a271674525d2856f3c5a2e62b/docs/guide-installation.md#alpine-linux

Will report back if it ends up looking different!

Thanks

**Comment by mateodelnorte** [comment]
looks like this still isn't working for me. :-\

```
FROM docker.gridpl.us/gridplus/node-alpine-artik-cross-build:latest AS build

RUN ["cross-build-start"]

RUN sudo apk add --no-cache make gcc g++ python linux-headers udev

ARG NPM_TOKEN

COPY package.json package.json

RUN JOBS=MAX npm install --build-from-source --unsafe-perm

COPY ./bin ./bin
COPY ./lib ./lib
COPY ./src ./src
COPY ./tests ./tests
COPY config.json config.json
COPY index.js index.js
COPY Makefile Makefile

RUN JOBS=MAX npm run build \
  && npm prune --production \
  && npm cache clean --force \
  && rm -rf /tmp/*

RUN ["cross-build-end"]
```
the grandparent container for the above build container is: 
```
FROM arm32v6/alpine:3.8
LABEL io.balena.architecture="armv7hf"

LABEL io.balena.qemu.version="3.0.0+resin-arm"

COPY qemu-arm-static /usr/bin
COPY resin-xbuild /usr/bin/resin-xbuild

ENV NODE_VERSION 10.10.0
ENV YARN_VERSION 1.6.0
```
and I've got another parent where I'm building and installing node. yes, lots of indirection, but all necessary for my arch and CI requirements.

**Comment by mateodelnorte** [comment]
Here's the failing error: 
```
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/serialport.cpp: In function 'void EIO_AfterDrain(uv_work_t*)':
../src/serialport.cpp:424:30: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->callback.Call(1, argv);
                              ^
In file included from ../src/./serialport.h:6:0,
                 from ../src/serialport.cpp:1:
../../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
../src/serialport_unix.cpp:24:26: fatal error: linux/serial.h: No such file or directory

                          ^
compilation terminated.
make: *** [bindings.target.mk:102: Release/obj.target/bindings/src/serialport_unix.o] Error 1
make: Leaving directory '/usr/src/service/node_modules/@serialport/bindings/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/service/node_modules/@serialport/bindings
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by mateodelnorte** [comment]
Turns out serial.h isn't in Alpine 3.8 for armv7l. Was able to get things building by pulling `linux-headers` from edge:
```
RUN apk add linux-headers --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main
```
