### ISSUE TITLE
Installs, but: Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by webtop** [node-serialport/node-serialport#1723]
- What are you trying to do?
Building a VS Code extension.

- What happens?
When the code encounters: var serialport = require("serialport");
I received the error:
Error: A dynamic link library (DLL) initialization routine failed.
\\?\K:\Development\Projects\micropython-ide-vscode\node_modules\@serialport\bindings\build\Release\bindings.node

- What should have happened?
I expected the code to run, after following all the instructions and https://github.com/nodejs/node-gyp#installation

- SerialPort@? N/A
- Node.js v? v8.11.3
- Windows? Linux? Mac? Windows 10 Pro 64bit
- Hardware and chipset? (Prolific/FTDI/Other) N/A
I have Python 2.7.5 installed, and npm does locate it

Steps I have taken:
npm install --global --production windows-build-tools
npm install -g node-gyp
npm install serialport --build-from-source

Errors I've encountered:
Not sure if this is relevant, but when I run node-gyp configure, I get:

> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.8.0
> gyp info using node@8.11.3 | win32 | x64
> gyp info spawn D:\Program Files (x86)\Python27\python.EXE
> gyp info spawn args [ 'C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'msvs',
> gyp info spawn args   '-G',
> gyp info spawn args   'msvs_version=2015',
> gyp info spawn args   '-I',
> gyp info spawn args   'K:\\Development\\Projects\\micropython-ide-vscode\\build\\config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\Paul\\.node-gyp\\8.11.3\\include\\node\\common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Paul\\.node-gyp\\8.11.3',
> gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
> gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Paul\\.node-gyp\\8.11.3\\<(target_arch)\\node.lib',
> gyp info spawn args   '-Dmodule_root_dir=K:\\Development\\Projects\\micropython-ide-vscode',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'K:\\Development\\Projects\\micropython-ide-vscode\\build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp: binding.gyp not found (cwd: K:\Development\Projects\micropython-ide-vscode) while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Paul\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:345:16)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "K:\\nodejs\\node.exe" "C:\\Users\\Paul\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
> gyp ERR! cwd K:\Development\Projects\micropython-ide-vscode
> gyp ERR! node -v v8.11.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok

Thanks for any help here.
Paul

**Comment by webtop** [comment]
That node-gyp issue I believe is unrelated, there is a bad reference in there for the location of the python binary.

**Comment by webtop** [comment]
If I navigate to "/k/Development/Projects/node_modules/@serialport/bindings" (in my case) and run "node-gyp configure" everything seems to build correctly.

**Comment by webtop** [comment]
Working now. Thx
